- type: startingGear
  id: CentcomWhistleblowerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChameleon
    back: ClothingBackpackSatchelHoldingCentcomWatchdogFilled
    shoes: ClothingShoesChameleonNoSlips
    mask: ClothingMaskGasChameleon
    head: ClothingHeadHatChameleon
    outerClothing: ClothingOuterArmorCentcommChameleon
    neck: ClothingNeckChameleon
    eyes: ClothingEyesGlassesCCDivHead
    gloves: ClothingAdmemeHandsInsulatedChameleon # Ronstation: This exists in the codebase already, removed the phoenix station version.
    id: ChameleonAgentPDA
    ears: ClothingHeadsetChameleonWatchdog
    pocket1: WeaponDisabler
    pocket2: Centcommteleportdoohickey
