- type: startingGear
  id: CentcomFormalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomFormal
    back: ClothingBackpackSatchelHoldingCentcomFormalFilled
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasCentcom
    outerClothing: ClothingOuterArmorCentcommCarapace
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesCentComm
    id: CentCommDivisionPDA
    ears: ClothingHeadsetAltCentComDivHead
    belt: BoxFolderCentComClipboardThreePapers
    pocket1: WeaponDisabler
    pocket2: WeaponRevolverMateba
  inhand:
  - MindShieldImplanter
  - DeathRattleImplanterCentcomm

- type: startingGear
  id: CentcomInspectorGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCentcomFormalDress
    shoes: ClothingShoesBootsJackFilled
    mask: ClothingMaskGasCentcom
    outerClothing: ClothingOuterArmorCentcommCarapace
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesCentComm
    id: CentcomPDA
    ears: ClothingHeadsetAltCentComDivHead
    pocket1: WeaponDisabler
    pocket2: FlashlightSeclite
    suitstorage: OxygenTankFilled
  inhand:
  - BriefcaseCentcomInspector
- type: startingGear
#This became very specific to Semper, so I'm just gona mark it as the relevant name
#Yes, if you want a loadout for your CC character, I'll make it. (if it doesn't require custom fills, the CCO loadout is connected to "CentcommGear", and your character's loadout for CCO should apply when setting it via debug outfits. CentcomFormal has a custom fill that was made with admin cc characters in mind, and has the flexible ID.)
  id: CentcomSecDivHeadGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCentcommSecurityFormalWear
    back: ClothingBackpackHoldingCentcomOfficerFilled
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatCentcomcap
    mask: ClothingMaskGasCentcom
    neck: ClothingNeckCloakCCSDFireline
    outerClothing: ClothingOuterArmorCentcommCarapace
    gloves: ClothingHandsGlovesCentComm
    eyes: ClothingEyesHudCCDivHead
    id: CentCommDivisionPDA
    ears: ClothingHeadsetAltCentComDivHead
    belt: CentcommVibrobladeSheathFilled
    pocket1: WeaponEnergyMagnumGunGreenshield
    pocket2: WeaponPistolStechkin
    suitstorage: WeaponRifleL10
  inhand:
  - MindShieldImplanter
  - DeathRattleImplanterCentcomm

- type: startingGear
  id: CentcomBorgiGear
  equipment:
    back: ClothingBackpackSatchelHoldingCentcomFormalFilled
    outerClothing: ClothingOuterHardsuitERTEngineer
    eyes: ClothingEyesGlassesCentComm
    id: CentCommDivisionPDA
    ears: ClothingHeadsetAltCentComDivHead
    pocket1: WeaponDisabler
  inhand:
  - MindShieldImplanter
  - DeathRattleImplanterCentcomm
