- type: job
  id: NTNCBlueShield
  name: job-name-ntncblueshield
  description: job-description-ntncblueshield
  playTimeTracker: JobConsortiumBlueShield
# Ronstation start: whitelist CC roles to prevent abuse, don't need role reqs when its whitelisted
#  requirements:
#  - !type:OverallPlaytimeRequirement
#    time: 72000 # 20h
#  - !type:RoleTimeRequirement
#    role: JobSecurityOfficer
#    time: 18000 # 5h
  whitelisted: true #Ronstation end
  setPreference: false
  startingGear: NTNCHardsuitGear
  icon: JobIconNTNCBlueShield
  rules: job-rules-corporate-aligned
  supervisors: job-supervisors-centcom
  bypassEorPacification: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant, DeathRattleImplantNanoTrasen, RadioImplantNanoTrasen ]
