- type: job
  id: CentralCommandOfficial
  name: job-name-centcommoff
  description: job-description-centcommoff
  playTimeTracker: JobCentralCommandOfficial
  #Ronstation start: whitelist CC roles to prevent abuse, don't need role reqs when its whitelisted
  #requirements:
  #- !type:RolesRequirement
  #  proto: StaffAndMentorOnlyRolesReq
  whitelisted: true # Ronstation end
  setPreference: false
  startingGear: CentcommGear
  icon: "JobIconCentralCommandOfficial" #Starlight
  supervisors: job-supervisors-hos
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentcommGear
  equipment:
    jumpsuit: ClothingAltUniformJumpsuitCentcomOfficial # alt version
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorCentcommCarapace
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
    pocket1: BoxFolderCentComClipboardThreePapers
    pocket2: PenCentcom


- type: chameleonOutfit
  id: CentralCommandOfficialOutfit
  job: CentralCommandOfficial
  hasMindShield: true
  equipment:
    neck: ClothingNeckScarfStripedCentcom
    mask: ClothingMaskGasCentcom
