- type: job
  id: CentralCommandOfficial
  name: job-name-centcommoff
  description: job-description-centcommoff
  playTimeTracker: JobCentralCommandOfficial
  requirements:
  - !type:RolesRequirement
    proto: StaffAndMentorOnlyRolesReq
  setPreference: true # Ronstation: port phoenix station CCO loadout
  startingGear: CentcommGear
  icon: "JobIconCentralCommandOfficial" #Starlight
  supervisors: job-supervisors-hos
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentcommGear
  equipment:
    # Phoenix start - Loadouts for roundstart CC
    #jumpsuit: ClothingAltUniformJumpsuitCentcomOfficial # alt version
    #shoes: ClothingShoesBootsCombatFilled
    #head: ClothingHeadHatCentcom
    #eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorCentcommCarapace
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    #belt: WeaponPistolN1984 # Phoenix - Loadouts for roundstart CC
    pocket1: BoxFolderCentComClipboardThreePapers
    pocket2: PenCentcom
    #back: ClothingBackpackSatchelLeather # Phoenix - Loadouts for roundstart CC
  inhand:
    - Centcommteleportdoohickey # Phoenix - For them to get to CC if they latejoin.
  storage:
    back:
      - DoorRemoteCustom
      - GreenPhone
      - RubberStampCentcom
  # Phoenix end - Loadouts for roundstart CC


- type: chameleonOutfit
  id: CentralCommandOfficialOutfit
  job: CentralCommandOfficial
  hasMindShield: true
  equipment:
    neck: ClothingNeckScarfStripedCentcom
    mask: ClothingMaskGasCentcom
