- type: job
  id: CentralCommandOfficial
  name: job-name-centcommoff
  description: job-description-centcommoff
  playTimeTracker: JobCentralCommandOfficial
  #Ronstation start: whitelist CC roles to prevent abuse, don't need role reqs when its whitelisted
  #requirements:
  #- !type:RolesRequirement
  #  proto: StaffAndMentorOnlyRolesReq
  whitelisted: true # Ronstation end
  setPreference: true # Ronstation: port phoenix station CCO loadout
  startingGear: CentcommGear
  icon: "JobIconCentralCommandOfficial" #Starlight
  supervisors: job-supervisors-hos
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm, CommandTrackingImplant ] # Ronstation: Less pain for the BSO.

- type: startingGear
  id: CentcommGear
  equipment:
    #Ronstation start - porting Phoenix Station Loadouts + some extra additions/polish
    #jumpsuit: ClothingAltUniformJumpsuitCentcomOfficial # alt version
    #shoes: ClothingShoesBootsCombatFilled
    #head: ClothingHeadHatCentcom
    #eyes: ClothingEyesGlassesCentComm
    # gloves: ClothingHandsGlovesColorBlack Ronstation: Replaced by the selectable gloves category
    outerClothing: ClothingOuterArmorCentcommCarapace
    id: CentCommDivisionPDA #Ronstation: Custom PDA/ID for CC Officials to change their information for in-character purposes
    ears: ClothingHeadsetAltCentComDivHead #Ronstation: Actually use the CC headset with admeme-safe components, keys you can't remove since there should only be so many master keys in a round for objectives.
    #belt: WeaponPistolN1984
    pocket1: BoxFolderCentComClipboardThreePapers
    #pocket2: PenCentcom
    inhand:
    - Centcommteleportdoohickey # Phoenix - For them to get to CC if they latejoin.
    storage:
     back:
      - DoorRemoteCustom
      - GreenPhone
      - RubberStampCentcom
    #Ronstation end - porting Phoenix Station Loadouts + some extra additions/polish

- type: chameleonOutfit
  id: CentralCommandOfficialOutfit
  job: CentralCommandOfficial
  hasMindShield: true
  equipment:
    neck: ClothingNeckScarfStripedCentcom
    mask: ClothingMaskGasCentcom
